name: stringee_flutter_plugin
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  toast:

flutter:
  plugin:
    androidPackage: com.stringee.stringeeflutterplugin
    pluginClass: StringeeFlutterPlugin

